[package]
name = "infra"
version = "0.1.0"
edition = "2024"

[dependencies]
hex-literal = "1.1.0"
sha2 = "0.10.9"
tracing = "0.1.43"
tracing-journald = "0.3.2"
tracing-panic = "0.1.2"
tracing-subscriber = { version = "0.3.22", features = ["fmt", "ansi", "env-filter"] }
