[package]
name = "kubernetes"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
russh = "0.54.6"
shell-escape = "0.1.5"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt", "ansi", "env-filter"] }
